config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts, only: [:index, :new, :create, :destroy, :show] do
    collection do
      get 'search'
    end  
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
  # いいね機能にバリデーションをつけます。具体的に何をするのかというと、
  # 1人が１つの投稿に対して、１つしかいいねをつけられないようにします。
  # （今回は自分の投稿にもいいねができます)
  # validates_uniqueness_ofによって、post_idとuser_id　の組が1組しかないようにバリデーションをかけました。
  
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  def self.search(search)
    if search
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.create(post_id: params[:post_id])
    @like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end
  def new 
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end
  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end
  def search
    @posts = Post.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end
  private
  def post_params
    params.require(:post).permit(:name, :image, :text).merge(user_id: current_user.id)
    # postの情報を持つハッシュと、user_idを持つハッシュを結合させます。
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffeeblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="header">
      <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
      <h3 class="title"><a href="/">Coffeeblog</a></h3>
      <div class="menu">
        <% if user_signed_in? %>
          <div class="menulist">
            <%= link_to "ログアウト", destroy_user_session_path, class: "logout", method: :delete %>
            <%= link_to "投稿する", new_post_path, class: "post" %>
            <%= link_to "ユーザー一覧", users_path, class: "userlist"%>
          </div>
        <% else %> 
          <div class="loginlist">
            <%= link_to "ログイン", new_user_session_path, class: "login" %>
            <%= link_to "新規登録", new_user_registration_path, class: "register" %>
          </div>
        <% end %>
       </div>  
    </div>
    <%= yield %>
  </body>  
</html>

app/views/likes/_like.html.erb
<% if current_user.already_liked?(@post) %>
  <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete, remote: true %>
<% else %>
  <%= button_to 'いいね', post_likes_path(@post), remote: true %>
<% end %>
<h4>いいねしたユーザー</h4>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/posts/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="reset.css">
  <link rel="stylesheet" href="style.css">
  <title>Coffeeblog</title>
</head>
<Body>
  <div class= "mainwrap">
  <%= image_tag "/nathan-dumlao-6VhPY27jdps-unsplash.jpg", width: "370px"%>
  <%= image_tag "/karl-fredrickson-TYIzeCiZ_60-unsplash.jpg", width: "370px"%>
  <%= image_tag "/cathryn-lavery-NsWcRlBT_74-unsplash.jpg", width: "370px"%>
    <div class= "gridlist">
      <div class ="pickup">
        <h2>イチオシ投稿</h2>
      </div>
      <div class="section">
        <% @posts.each do |post| %>
          <p><a href="/posts/<%= post.id %>"><%= post.name %></a></p>
          <h6><%= link_to '削除', post_path(post.id), method: :delete %></h6>
          <h6>いいね<%= post.like_ids.count %></h6>
        <% end %>
      </div>
    </div>
    <div class=rightcontent>
      <div class="event">
        <h3>全国のイベント</h3>
      </div>
      <div class= "venue">
        <div class= "region1">
          <h3>関東</h3>
          <h4>SCAJ ワールドスペシャルティコーヒーカンファレンス 2020</h4>
          <p>場所：【有明】東京ビッグサイト<br>
          日程：10月14日(水) ~ 16日(金)<br>
          ホームページ：
          <%= link_to "http://www.scajconference.jp/"%>
          </p>
        </div>
        <div class="region2">
          <h3>北陸</h3>
          <h4>Japan Coffee Festival in 越前市</h4>
          <p>場所：【越前市】場所未定<br>
          日程：12月5日(土) ~ 6日(日)<br>
          ホームページ：
          <%= link_to "japancoffeefestival.com/japan-coffee-festival/"%>
          </p>
        </div>
      </div>
     </div>   
</Body>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="reset.css">
  <link rel="stylesheet" href="style.css">
  <title>Coffeeblog</title>
</head>
<div class="contents">
  <div class="container">
  <h3>投稿フォーム</h3>
    <%= form_with(model: @post, local: true) do |form| %>
      <%= form.text_field :name, placeholder: "Name", class: "text" %>
      <%= form.text_field :image, placeholder: "Image Url", class: "text" %>
      <%= form.text_area :text, placeholder: "text", rows: "10", class: "text" %>
      <%= form.submit "投稿する", class: "text"%>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<div class= "postlist">
<h4>投稿一覧</h4>
  <div class= "each">
    <% @posts.each do |post| %>
    <p><a href="/posts/<%= post.id %>", class="blogname"><%= post.name %></a></p>
    <h5><%= post.text %></h5>   
    <% end %>
  </div>  
</div>  

app/views/posts/show.html.erb
<div class= "background"></div>
<div class="detail">
  <h3>投稿詳細ページ</h3>
  <h4><%= @post.user.email %></h4>
  <%= @post.image %>
  <h4><%= @post.text %></h4>
  <h4>いいね件数: <%= @post.likes.count %></h4>
  <div id="likes_buttons_<%= @post.id %>">
    <%= render partial: 'likes/like', locals: { post: @post} %>
  </div>
  <%= link_to "ホームへ戻る", posts_path %>
</div>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"><%= user.email %></a>
  <hr>
<% end %>
<%= link_to "ホームへ戻る", posts_path %>

app/views/users/show.html.erb
<h1>ユーザー詳細ページ</h1>
<h3><%= @user.email %></h3>
<h2>投稿内容</h2>
<% @user.posts.each do |post| %>
<%= post.text %> 
  <hr>
<% end %>
<%= link_to "ユーザー一覧へ", users_path %>
<%= link_to "ホームへ戻る", posts_path %>